version: '3.9'
services:

  auth-service:
    build: ./auth-service
    ports: 
      - "8010:8010"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    networks:
      - microservices-net
    ports:
      - "80:80"

  documents-service:
    build: ./src/documents-service
    ports: 
      - "8011:8011"
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge

